import newCodeReviewMessage from 'slack/new-code-review-message';

test('returns properly formatted slack message when there is no description', () => {
  expect.assertions(1);

  const githubPayload = {
    "url": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/51',
    "id": 789454079,
    "node_id": 'PR_kwDOGLXuLc4vDhz_',
    "html_url": 'https://github.com/startstackin/stackin-web-account/pull/51',
    "diff_url": 'https://github.com/startstackin/stackin-web-account/pull/51.diff',
    "patch_url": 'https://github.com/startstackin/stackin-web-account/pull/51.patch',
    "issue_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/51',
    "number": 51,
    "state": 'open',
    "locked": false,
    "title": 'feat(STK-1073): Created tracking service ',
    "user": {
      "login": 'theCybulski',
      "id": 44953771,
      "node_id": 'MDQ6VXNlcjQ0OTUzNzcx',
      "avatar_url": 'https://avatars.githubusercontent.com/u/44953771?v=4',
      "gravatar_id": '',
      "url": 'https://api.github.com/users/theCybulski',
      "html_url": 'https://github.com/theCybulski',
      "followers_url": 'https://api.github.com/users/theCybulski/followers',
      "following_url": 'https://api.github.com/users/theCybulski/following{/other_user}',
      "gists_url": 'https://api.github.com/users/theCybulski/gists{/gist_id}',
      "starred_url": 'https://api.github.com/users/theCybulski/starred{/owner}{/repo}',
      "subscriptions_url": 'https://api.github.com/users/theCybulski/subscriptions',
      "organizations_url": 'https://api.github.com/users/theCybulski/orgs',
      "repos_url": 'https://api.github.com/users/theCybulski/repos',
      "events_url": 'https://api.github.com/users/theCybulski/events{/privacy}',
      "received_events_url": 'https://api.github.com/users/theCybulski/received_events',
      "type": 'User',
      "site_admin": false
    },
    "body": null,
    "created_at": '2021-11-26T10:41:06Z',
    "updated_at": '2021-11-26T14:00:44Z',
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": '4ae4dec5fb9be43458929d67b74f1c0dc7fef431',
    "assignee": null,
    "assignees": [],
    "requested_reviewers": [],
    "requested_teams": [],
    "labels": [],
    "milestone": null,
    "draft": false,
    "commits_url": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/51/commits',
    "review_comments_url": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/51/comments',
    "review_comment_url": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/comments{/number}',
    "comments_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/51/comments',
    "statuses_url": 'https://api.github.com/repos/startstackin/stackin-web-account/statuses/51c34a72bf58eeeb3e53ebace9ceee6e6ad5b406',
    "head": {
      "label": 'startstackin:STK-1073-tracking',
      "ref": 'STK-1073-tracking',
      "sha": '51c34a72bf58eeeb3e53ebace9ceee6e6ad5b406',
      "user": {
        "login": 'startstackin',
        "id": 57962921,
        "node_id": 'MDEyOk9yZ2FuaXphdGlvbjU3OTYyOTIx',
        "avatar_url": 'https://avatars.githubusercontent.com/u/57962921?v=4',
        "gravatar_id": '',
        "url": 'https://api.github.com/users/startstackin',
        "html_url": 'https://github.com/startstackin',
        "followers_url": 'https://api.github.com/users/startstackin/followers',
        "following_url": 'https://api.github.com/users/startstackin/following{/other_user}',
        "gists_url": 'https://api.github.com/users/startstackin/gists{/gist_id}',
        "starred_url": 'https://api.github.com/users/startstackin/starred{/owner}{/repo}',
        "subscriptions_url": 'https://api.github.com/users/startstackin/subscriptions',
        "organizations_url": 'https://api.github.com/users/startstackin/orgs',
        "repos_url": 'https://api.github.com/users/startstackin/repos',
        "events_url": 'https://api.github.com/users/startstackin/events{/privacy}',
        "received_events_url": 'https://api.github.com/users/startstackin/received_events',
        "type": 'Organization',
        "site_admin": false
      },
      "repo": {
        "id": 414576173,
        "node_id": 'R_kgDOGLXuLQ',
        "name": 'stackin-web-account',
        "full_name": 'startstackin/stackin-web-account',
        "private": false,
        "owner": [Object],
        "html_url": 'https://github.com/startstackin/stackin-web-account',
        "description": null,
        "fork": false,
        "url": 'https://api.github.com/repos/startstackin/stackin-web-account',
        "forks_url": 'https://api.github.com/repos/startstackin/stackin-web-account/forks',
        "keys_url": 'https://api.github.com/repos/startstackin/stackin-web-account/keys{/key_id}',
        "collaborators_url": 'https://api.github.com/repos/startstackin/stackin-web-account/collaborators{/collaborator}',
        "teams_url": 'https://api.github.com/repos/startstackin/stackin-web-account/teams',
        "hooks_url": 'https://api.github.com/repos/startstackin/stackin-web-account/hooks',
        "issue_events_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/events{/number}',
        "events_url": 'https://api.github.com/repos/startstackin/stackin-web-account/events',
        "assignees_url": 'https://api.github.com/repos/startstackin/stackin-web-account/assignees{/user}',
        "branches_url": 'https://api.github.com/repos/startstackin/stackin-web-account/branches{/branch}',
        "tags_url": 'https://api.github.com/repos/startstackin/stackin-web-account/tags',
        "blobs_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/blobs{/sha}',
        "git_tags_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/tags{/sha}',
        "git_refs_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/refs{/sha}',
        "trees_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/trees{/sha}',
        "statuses_url": 'https://api.github.com/repos/startstackin/stackin-web-account/statuses/{sha}',
        "languages_url": 'https://api.github.com/repos/startstackin/stackin-web-account/languages',
        "stargazers_url": 'https://api.github.com/repos/startstackin/stackin-web-account/stargazers',
        "contributors_url": 'https://api.github.com/repos/startstackin/stackin-web-account/contributors',
        "subscribers_url": 'https://api.github.com/repos/startstackin/stackin-web-account/subscribers',
        "subscription_url": 'https://api.github.com/repos/startstackin/stackin-web-account/subscription',
        "commits_url": 'https://api.github.com/repos/startstackin/stackin-web-account/commits{/sha}',
        "git_commits_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/commits{/sha}',
        "comments_url": 'https://api.github.com/repos/startstackin/stackin-web-account/comments{/number}',
        "issue_comment_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/comments{/number}',
        "contents_url": 'https://api.github.com/repos/startstackin/stackin-web-account/contents/{+path}',
        "compare_url": 'https://api.github.com/repos/startstackin/stackin-web-account/compare/{base}...{head}',
        "merges_url": 'https://api.github.com/repos/startstackin/stackin-web-account/merges',
        "archive_url": 'https://api.github.com/repos/startstackin/stackin-web-account/{archive_format}{/ref}',
        "downloads_url": 'https://api.github.com/repos/startstackin/stackin-web-account/downloads',
        "issues_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues{/number}',
        "pulls_url": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls{/number}',
        "milestones_url": 'https://api.github.com/repos/startstackin/stackin-web-account/milestones{/number}',
        "notifications_url": 'https://api.github.com/repos/startstackin/stackin-web-account/notifications{?since,all,participating}',
        "labels_url": 'https://api.github.com/repos/startstackin/stackin-web-account/labels{/name}',
        "releases_url": 'https://api.github.com/repos/startstackin/stackin-web-account/releases{/id}',
        "deployments_url": 'https://api.github.com/repos/startstackin/stackin-web-account/deployments',
        "created_at": '2021-10-07T11:38:04Z',
        "updated_at": '2021-11-26T09:52:06Z',
        "pushed_at": '2021-11-26T14:00:44Z',
        "git_url": 'git://github.com/startstackin/stackin-web-account.git',
        "ssh_url": 'git@github.com:startstackin/stackin-web-account.git',
        "clone_url": 'https://github.com/startstackin/stackin-web-account.git',
        "svn_url": 'https://github.com/startstackin/stackin-web-account',
        "homepage": null,
        "size": 5780,
        "language": 'TypeScript',
        "mirror_url": null,
        "visibility": 'private',
        "default_branch": 'master'
      }
    },
    "base": {
      "label": 'startstackin:master',
      "ref": 'master',
      "sha": '282b56e5a77fa6f9980f6c60dbbeedc5774f8b24',
      "user": {
        "login": 'startstackin',
        "id": 57962921,
        "node_id": 'MDEyOk9yZ2FuaXphdGlvbjU3OTYyOTIx',
        "avatar_url": 'https://avatars.githubusercontent.com/u/57962921?v=4',
        "gravatar_id": '',
        "url": 'https://api.github.com/users/startstackin',
        "html_url": 'https://github.com/startstackin',
        "followers_url": 'https://api.github.com/users/startstackin/followers',
        "following_url": 'https://api.github.com/users/startstackin/following{/other_user}',
        "gists_url": 'https://api.github.com/users/startstackin/gists{/gist_id}',
        "starred_url": 'https://api.github.com/users/startstackin/starred{/owner}{/repo}',
        "subscriptions_url": 'https://api.github.com/users/startstackin/subscriptions',
        "organizations_url": 'https://api.github.com/users/startstackin/orgs',
        "repos_url": 'https://api.github.com/users/startstackin/repos',
        "events_url": 'https://api.github.com/users/startstackin/events{/privacy}',
        "received_events_url": 'https://api.github.com/users/startstackin/received_events',
        "type": 'Organization'
      },
      "repo": {
        "id": 414576173,
        "node_id": 'R_kgDOGLXuLQ',
        "name": 'stackin-web-account',
        "full_name": 'startstackin/stackin-web-account',
        "private": false,
        "owner": [Object],
        "html_url": 'https://github.com/startstackin/stackin-web-account',
        "description": null,
        "fork": false,
        "url": 'https://api.github.com/repos/startstackin/stackin-web-account',
        "forks_url": 'https://api.github.com/repos/startstackin/stackin-web-account/forks',
        "keys_url": 'https://api.github.com/repos/startstackin/stackin-web-account/keys{/key_id}',
        "collaborators_url": 'https://api.github.com/repos/startstackin/stackin-web-account/collaborators{/collaborator}',
        "teams_url": 'https://api.github.com/repos/startstackin/stackin-web-account/teams',
        "hooks_url": 'https://api.github.com/repos/startstackin/stackin-web-account/hooks',
        "issue_events_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/events{/number}',
        "events_url": 'https://api.github.com/repos/startstackin/stackin-web-account/events',
        "assignees_url": 'https://api.github.com/repos/startstackin/stackin-web-account/assignees{/user}',
        "branches_url": 'https://api.github.com/repos/startstackin/stackin-web-account/branches{/branch}',
        "tags_url": 'https://api.github.com/repos/startstackin/stackin-web-account/tags',
        "blobs_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/blobs{/sha}',
        "git_tags_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/tags{/sha}',
        "git_refs_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/refs{/sha}',
        "trees_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/trees{/sha}',
        "statuses_url": 'https://api.github.com/repos/startstackin/stackin-web-account/statuses/{sha}',
        "languages_url": 'https://api.github.com/repos/startstackin/stackin-web-account/languages',
        "stargazers_url": 'https://api.github.com/repos/startstackin/stackin-web-account/stargazers',
        "contributors_url": 'https://api.github.com/repos/startstackin/stackin-web-account/contributors',
        "subscribers_url": 'https://api.github.com/repos/startstackin/stackin-web-account/subscribers',
        "subscription_url": 'https://api.github.com/repos/startstackin/stackin-web-account/subscription',
        "commits_url": 'https://api.github.com/repos/startstackin/stackin-web-account/commits{/sha}',
        "git_commits_url": 'https://api.github.com/repos/startstackin/stackin-web-account/git/commits{/sha}',
        "comments_url": 'https://api.github.com/repos/startstackin/stackin-web-account/comments{/number}',
        "issue_comment_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/comments{/number}',
        "contents_url": 'https://api.github.com/repos/startstackin/stackin-web-account/contents/{+path}',
        "compare_url": 'https://api.github.com/repos/startstackin/stackin-web-account/compare/{base}...{head}',
        "merges_url": 'https://api.github.com/repos/startstackin/stackin-web-account/merges',
        "archive_url": 'https://api.github.com/repos/startstackin/stackin-web-account/{archive_format}{/ref}',
        "downloads_url": 'https://api.github.com/repos/startstackin/stackin-web-account/downloads',
        "issues_url": 'https://api.github.com/repos/startstackin/stackin-web-account/issues{/number}',
        "pulls_url": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls{/number}',
        "milestones_url": 'https://api.github.com/repos/startstackin/stackin-web-account/milestones{/number}',
        "notifications_url": 'https://api.github.com/repos/startstackin/stackin-web-account/notifications{?since,all,participating}',
        "labels_url": 'https://api.github.com/repos/startstackin/stackin-web-account/labels{/name}',
        "releases_url": 'https://api.github.com/repos/startstackin/stackin-web-account/releases{/id}',
        "deployments_url": 'https://api.github.com/repos/startstackin/stackin-web-account/deployments',
        "created_at": '2021-10-07T11:38:04Z',
        "updated_at": '2021-11-26T09:52:06Z',
        "pushed_at": '2021-11-26T14:00:44Z',
        "git_url": 'git://github.com/startstackin/stackin-web-account.git',
        "ssh_url": 'git@github.com:startstackin/stackin-web-account.git',
        "clone_url": 'https://github.com/startstackin/stackin-web-account.git',
        "svn_url": 'https://github.com/startstackin/stackin-web-account',
        "default_branch": 'master'
      }
    },
    "_links": {
      "self": {
        "href": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/51'
      },
      "html": {
        "href": 'https://github.com/startstackin/stackin-web-account/pull/51'
      },
      "issue": {
        "href": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/51'
      },
      "comments": {
        "href": 'https://api.github.com/repos/startstackin/stackin-web-account/issues/51/comments'
      },
      "review_comments": {
        "href": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/51/comments'
      },
      "review_comment": {
        "href": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/comments{/number}'
      },
      "commits": {
        "href": 'https://api.github.com/repos/startstackin/stackin-web-account/pulls/51/commits'
      },
      "statuses": {
        "href": 'https://api.github.com/repos/startstackin/stackin-web-account/statuses/51c34a72bf58eeeb3e53ebace9ceee6e6ad5b406'
      }
    },
    "author_association": 'CONTRIBUTOR',
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": false,
    "mergeable": true,
    "rebaseable": true,
    "mergeable_state": 'blocked',
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 158,
    "deletions": 8,
    "changed_files": 11
  }

  return expect(newCodeReviewMessage(githubPayload)).toEqual([
    {
      "actions": [
        {
          "name": "review",
          "text": ":eyeglasses: Code review",
          "type": "button",
          "value": "review"
        }
      ],
      "author_icon": "https://avatars.githubusercontent.com/u/44953771?v=4",
      "author_link": "https://api.github.com/users/theCybulski",
      "author_name": "theCybulski",
      "callback_id": "review_action",
      "color": "#e1e4e8",
      "fields": [
        {
          "short": true,
          "title": "+158 -8",
          "value": "LOC changed in *11* files"
        },
        {
          "short": true,
          "title": "1",
          "value": "Commits"
        }
      ],
      "footer": "Github API",
      "footer_icon": "https://d2bbtvgnhux6eq.cloudfront.net/assets/favicon-github-0332aa660c6548e285079410739397df.png",
      "mrkdwn_in": ["pretext", "text", "fields"],
      "text": "",
      "title": "feat(STK-1073): Created tracking service ",
      "title_link": "https://github.com/startstackin/stackin-web-account/pull/51",
      "ts": 1637923266
    }
  ])
});
